### ISSUE TITLE
Document how to connect internally over SSL

### ISSUE THREAD

**Issue by simonseddon** [docker-mate/docker-mate#7]
I've had a great time using docker-mate - so first of all, thank you.

I've ran in to an issue when using the popular Guzzle library in combination with SSL and Wordpress. Everything else has worked fine until this point.

Using Wordpress functions to get my site URL (let's say https://project.docker for convenience) and appending a path (wp-json/path/path/etc) gives me a Guzzle error 7: (`Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to project.docker port 443: Connection refused`). Of course, if I visit the correspoding URL in my browser, I get the JSON output as expected. It's just that Guzzle can't access it from within the container.

Any advice? I've hit a brick wall testing EXPOSE, PORTS, host file edits, etc. etc.

**Comment by xf-** [comment]
Dinghy proxy (terminates SSL) → forwards to correct Container on port 80 (no SSL/443 in your container).

**DNS**
*.docker properly points to 127.0.0.1, because it is the easiest, so you request inside the container never gets outside the Container and no dinghy.

**Workaround/Solution DNS**
Set your *.docker to your local IP like 10.10.10.10 or 192.168.5.5. This IP can change depending on lease settings of your DHCP and the network you are connected to.

**OR**

**Workaround/Solution WordPress**
Different articles about using WordPress behind a proxy for SSL termination
https://www.feliciano.tech/blog/running-wordpress-behind-an-sslhttps-terminating-proxy/

Sorry missed the issue notification

**Comment by xf-** [comment]
@simonseddon solves this your issue/question?

**Comment by simonseddon** [comment]
@xf-  thanks for the very informative response. That solves it, thank you!
